version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/app/docs
      - ./src:/app/src
    depends_on:
      - ollama
      - qdrant
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=edatajanus;AccountKey=W5y7X1c84AHm8BSBwM0DJPy6KWIHm6HI;EndpointSuffix=core.windows.net
      - AZURE_CONTAINER_NAME=docs-container
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all  # Habilita GPU, se disponível
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull llama3:8b && wait"]

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  ollama:
  qdrant_data: